
FROM ubuntu:20.04
ARG VERSION="dev"

RUN apt-get update && \
 apt-get install --no-install-recommends -q --assume-yes openjdk-17-jre-headless=17* && \
 apt-get clean  && \
 rm -rf /var/lib/apt/lists/*  && \

USER root
ADD . /